### ISSUE TITLE
剪枝效果

### ISSUE THREAD

**Issue by 520jefferson** [airaria/TextPruner#1]
剪枝在稀疏化的范畴内。但剪枝比较senstive一点，剪枝减少了op的理论TFLOPS需求，但有可能会导致与HW Matrix Accelerator不匹配，使得剪后的op的TFLOPS efficiency下降，有可能会起反作用。

**Comment by airaria** [comment]
你好，感谢你的关注。
关于你的问题，我理解的要表达的意思是矩阵稀疏性影响运算效率？
补充说明的一点是TextPruner执行的是结构化裁剪，裁剪矩阵的整行或整列，而非置某些元素为0，从而不影响稀疏性。

**Comment by 520jefferson** [comment]
> 你好，感谢你的关注。 关于你的问题，我理解的要表达的意思是矩阵稀疏性影响运算效率？ 补充说明的一点是TextPruner执行的是结构化裁剪，裁剪矩阵的整行或整列，而非置某些元素为0，从而不影响稀疏性。

赞，那也就是说使用剪枝工具后再使用推理优化的一些措施比如tensorrt，faster transformer等手段可以进一步加速对吧？特别是针对几十亿甚至上百亿的模型，剪枝很难将速度一步降到位，再考虑指标的情况下

**Comment by airaria** [comment]
> > 你好，感谢你的关注。 关于你的问题，我理解的要表达的意思是矩阵稀疏性影响运算效率？ 补充说明的一点是TextPruner执行的是结构化裁剪，裁剪矩阵的整行或整列，而非置某些元素为0，从而不影响稀疏性。
> 
> 赞，那也就是说使用剪枝工具后再使用推理优化的一些措施比如tensorrt，faster transformer等手段可以进一步加速对吧？特别是针对几十亿甚至上百亿的模型，剪枝很难将速度一步降到位，再考虑指标的情况下

是的，剪枝与其他手段不冲突，配合其他优化手段一起用最好
