### ISSUE TITLE
使用trainer训练的electra进行裁剪报错了。找不到原因啊

### ISSUE THREAD

**Issue by cyjack** [airaria/TextPruner#11]
return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by airaria** [comment]
> ```
> return F.linear(input, self.weight, self.bias)
> ```
> 
> 
>     
>   
> 
> RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

裁剪其他模型有问题吗

**Comment by cyjack** [comment]
> 
bert给的官方的没有问题。

**Comment by cyjack** [comment]
> > ```
> > return F.linear(input, self.weight, self.bias)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
> 
> 裁剪其他模型有问题吗
bert给的官方示例没有问题。

**Comment by airaria** [comment]
> > ```
> > return F.linear(input, self.weight, self.bias)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
> 
> 
> 裁剪其他模型有问题吗
> bert给的官方示例没有问题。

我将例子里的transformer_pruning/transformer_pruning.py修改成裁剪electra，裁剪electra-small-discriminator并没有问题。
你的报错具体是发生在何处？
尝试不用CUDA而在CPU上运行是否报错？
