### ISSUE TITLE
使用VocabularyPruner时报错：

### ISSUE THREAD

**Issue by Chenzongchao** [airaria/TextPruner#14]
报错信息
 CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

代码如下：
from textpruner import VocabularyPruner
pruner = VocabularyPruner(model, tokenizer)
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
checkpoint = "bigscience/mt0-small"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
pruner.prune(dataiter=retain_word)

**Comment by airaria** [comment]
Fixed, and use T5Tokenizer instead of AutoTokenizer
已修复，用最新的代码试试。
另外，不要用AutoTokenizer，用T5Tokenizer
```python
from textpruner import VocabularyPruner
from transformers import AutoModelForSeq2SeqLM, T5Tokenizer
checkpoint = "bigscience/mt0-small"
tokenizer = T5Tokenizer.from_pretrained(checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
pruner = VocabularyPruner(model, tokenizer)
pruner.prune(dataiter=["This is a string."])
```
