### ISSUE TITLE
T5模型的剪枝

### ISSUE THREAD

**Issue by acceleratelch** [airaria/TextPruner#16]
看到README文档里提到对T5模型可以记进行Vocabulary Pruning，请问有没有示例代码呢。
并且看到T5翻译模型还不能进行Transformer Pruning，请问后续还会更新支持T5的Transformer Pruning吗

**Comment by airaria** [comment]
对T5进行词表裁剪可以参考这个例子
https://github.com/airaria/TextPruner/tree/main/examples/vocabulary_pruning#pruning-the-pre-trained-models-for-mlm
