### ISSUE TITLE
prune transformer hidden layer size

### ISSUE THREAD

**Issue by SunyanGu** [airaria/TextPruner#4]
I see that transformer pruning only changed ffn_size and num_of_heads。Can I ues this tool to purne transformer hidden layer size,like change 768 to 128?

**Comment by airaria** [comment]
Currently TextPruner does not support hidden size pruning.
















At 2022-03-10 17:43:27, "顾孙炎" ***@***.***> wrote:

I see that transformer pruning only changed ffn_size and num_of_heads。Can I ues this tool to purne transformer hidden layer size,like change 768 to 128?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
